<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sarvya-PC" failures="1" tests="1" name="ActiTimeTestCases.CustomerCreationTest" time="3.792" errors="0" timestamp="2024-03-11T17:48:51 IST" skipped="0">
  <testcase classname="ActiTimeTestCases.CustomerCreationTest" name="createCustAndProject" time="3.792">
    <failure message="Actual msg does not match with ecxpected msg expected [Customer &quot;Infosys&quot; has been successfully created.] but found [Customer &quot;Infosys20&quot; has been successfully created.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Actual msg does not match with ecxpected msg expected [Customer "Infosys" has been successfully created.] but found [Customer "Infosys20" has been successfully created.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at ActiTimeTestCases.CustomerCreationTest.createCustAndProject(CustomerCreationTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- createCustAndProject -->
</testsuite> <!-- ActiTimeTestCases.CustomerCreationTest -->
